### ISSUE TITLE
Fix `Collection was modified; enumeration operation may not execute.` error

### ISSUE THREAD

**Issue by andmos** [andmos/ReadingList#148]
After redeploy and cache is empty, a call to two lists can sometimes crash with:
```
2022-08-15 11:41:09.245 +00:00 [INF] {SourceContext="ReadingList.Trello.Helpers.ReadingListServiceProfiler"} GetReadingList: Call for list Reading took 2768 ms

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMJUMC53JN2P", Request id "0HMJUMC53JN2P:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at ReadingList.Trello.Services.ReadingListService.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Services/ReadingListService.cs:line 36
         at ReadingList.Trello.Services.CachedReadingListService.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Services/CachedReadingListService.cs:line 45
         at ReadingList.Trello.Helpers.ReadingListServiceProfiler.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Helpers/ReadingListServiceProfiler.cs:line 32
         at ReadingList.Carter.Modules.ReadingListModule.<AddRoutes>b__5_2(HttpRequest req, HttpResponse res) in /app/ReadingList.Carter/Modules/ReadingListModule.cs:line 50
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by andmos** [comment]
https://github.com/andmos/ReadingList/blob/ca603afeee2b7c211c8f48ec5081f0f81a443b35/ReadingList.Trello/Services/CachedReadingListService.cs#L36

**Comment by andmos** [comment]
After fix over:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMK13ECRF86N", Request id "0HMK13ECRF86N:00000002": An unhandled exception was thrown by the application.
      System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
         at System.Collections.Generic.List`1.Insert(Int32 index, T item)
         at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
         at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
         at Manatee.Trello.ReadOnlyListCollection.PerformRefresh(Boolean force, CancellationToken ct)
         at ReadingList.Trello.Services.ReadingListService.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Services/ReadingListService.cs:line 30
         at ReadingList.Trello.Services.CachedReadingListService.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Services/CachedReadingListService.cs:line 45
         at ReadingList.Trello.Helpers.ReadingListServiceProfiler.GetReadingList(String listName, String label) in /app/ReadingList.Trello/Helpers/ReadingListServiceProfiler.cs:line 32
         at ReadingList.Carter.Modules.ReadingListModule.<AddRoutes>b__5_0(HttpRequest req, HttpResponse res) in /app/ReadingList.Carter/Modules/ReadingListModule.cs:line 36
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
  ```
